USE AirTiquicia
GO
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[Destino]') AND type in (N'U'))
DROP TABLE [dbo].[Destino]
GO
/*
Crea tabla de Destino 

*/
CREATE TABLE dbo.Destino
(
IdDestino  INT NOT NULL IDENTITY(1,1),
Nombre VARCHAR(250) NOT NULL
)
ALTER TABLE dbo.Destino ADD CONSTRAINT [PK_Destino] PRIMARY KEY CLUSTERED
(
   IdDestino ASC 
) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
